#!/bin/sh
# postrm script for sleepi2-firmware
#
# see: dh_installdeb(1)

set -e

OVERLAY=sleepi2
CONFIG=/boot/config.txt

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        if [ -e $CONFIG ]; then
            sed $CONFIG -i -e "s@^(device_tree_|dt)overlay=${OVERLAY}.*\n@@"
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
